package evmos

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os/exec"

	"github.com/hanchon/hanchond/playground/filesmanager"
)

type STRv1 struct {
	Denom    string
	Exponent int
	Alias    string
	Name     string
	Symbol   string
}

func (e *Evmos) CreateSTRv1Proposal(params STRv1) (string, error) {
	metadata := fmt.Sprintf(`
{
  "messages": [
    {
      "@type": "/cosmos.gov.v1.MsgExecLegacyContent",
      "authority": "evmos10d07y265gmmuvt4z0w9aw880jnsr700jcrztvm",
      "content": {
        "@type": "/evmos.erc20.v1.RegisterCoinProposal",
        "description": "IBC coin to erc-20",
        "metadata":[
        {
            "denom_units": [
              {
                "denom": "%s",
                "exponent": %d,
                "aliases": [
                  "%s"
                ]
              }
            ],
            "base": "%s",
            "display": "%s",
            "name": "%s",
            "symbol": "%s"
      }
      ]
      }
    }
  ],
  "deposit": "1000000000`+e.BaseDenom+`",
  "title": "STRv1 proposal",
  "summary": "Registering a new coin."
}`, params.Denom, params.Exponent, params.Alias, params.Denom, params.Alias, params.Name, params.Symbol)

	path := "/tmp/metadata.json"
	filesmanager.DoesFileExist(path)
	if err := filesmanager.SaveFile([]byte(metadata), path); err != nil {
		return "", fmt.Errorf("could not save the proposal to disk:%s", err.Error())
	}

	command := exec.Command( //nolint:gosec
		filesmanager.GetEvmosdPath(e.Version),
		"tx",
		"gov",
		"submit-proposal",
		path,
		"--keyring-backend",
		e.KeyringBackend,
		"--home",
		e.HomeDir,
		"--node",
		fmt.Sprintf("http://localhost:%d", e.Ports.P26657),
		"--from",
		e.ValKeyName,
		"--gas-prices",
		fmt.Sprintf("100%s", e.BaseDenom),
		"--gas-adjustment",
		"4",
		"--gas",
		"2000000",
		"-y",
	)

	out, err := command.CombinedOutput()
	return string(out), err
}

func (e *Evmos) VoteOnProposal(proposalID string) error {
	command := exec.Command( //nolint:gosec
		filesmanager.GetEvmosdPath(e.Version),
		"tx",
		"gov",
		"vote",
		proposalID,
		"yes",
		"--keyring-backend",
		e.KeyringBackend,
		"--home",
		e.HomeDir,
		"--node",
		fmt.Sprintf("http://localhost:%d", e.Ports.P26657),
		"--from",
		e.ValKeyName,
		"--gas-prices",
		fmt.Sprintf("100%s", e.BaseDenom),
		"--gas-adjustment",
		"4",
		"-y",
	)

	out, err := command.CombinedOutput()
	fmt.Println(string(out))
	return err
}

func (e *Evmos) VoteOnAllTheProposals() error {
	type AutoGenerated struct {
		Proposals []struct {
			ProposalID string `json:"proposal_id"`
			Status     string `json:"status"`
		} `json:"proposals"`
	}
	// Query
	query := "cosmos/gov/v1beta1/proposals?pagination.limit=10&pagination.reverse=true"
	resp, err := http.Get(fmt.Sprintf("http://localhost:%d/%s", e.Ports.P1317, query))
	if err != nil {
		return err
	}
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("response not 200")
	}

	respbytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	var data AutoGenerated
	if err := json.Unmarshal(respbytes, &data); err != nil {
		return err
	}
	for _, v := range data.Proposals {
		if v.Status == "PROPOSAL_STATUS_VOTING_PERIOD" {
			// Votar
			if err := e.VoteOnProposal(v.ProposalID); err != nil {
				fmt.Printf("failed to vote on proposal: %s\n", v.ProposalID)
			}
		}
	}
	return nil
}

func (e *Evmos) CreateUpgradeProposal(upgradeHeight string) error {
	command := exec.Command( //nolint:gosec
		filesmanager.GetEvmosdPath(e.Version),
		"tx",
		"gov",
		"submit-legacy-proposal",
		"software-upgrade",
		"v19.0.0",
		"--title",
		"proposal",
		"--description",
		"description",
		"--upgrade-height",
		upgradeHeight,
		"--no-validate",
		"--deposit",
		"1000000000"+e.BaseDenom,
		"--keyring-backend",
		e.KeyringBackend,
		"--home",
		e.HomeDir,
		"--node",
		fmt.Sprintf("http://localhost:%d", e.Ports.P26657),
		"--from",
		e.ValKeyName,
		"--gas-prices",
		fmt.Sprintf("100%s", e.BaseDenom),
		"--gas-adjustment",
		"4",
		"--gas",
		"2000000",
		"-y",
	)

	out, err := command.CombinedOutput()
	fmt.Println(string(out))
	return err
}
