// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Block struct {
	ID         interface{}
	Height     int64
	Time       interface{}
	Txcount    int64
	Totalvalue interface{}
	Proposer   string
	Gasused    interface{}
	Gaslimit   interface{}
	Basefee    interface{}
	Hash       string
	Parenthash string
}
