// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type Block struct {
	ID      interface{}
	Height  int64
	Txcount int64
	Hash    string
}

type Transaction struct {
	ID          interface{}
	Cosmoshash  string
	Ethhash     string
	Typeurl     string
	Sender      string
	Blockheight int64
}
