name: Lint

on:
  pull_request:

permissions: read-all

jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v6.1.0
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: "env.GIT_DIFF"
